version: '3.7'
services:
  wanted-backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000

  wanted-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'wanted-database'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
